server:
  port: 8086
  servlet:
    context-path: "/ead-payment/"

spring:
  application:
    name: ead-payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead_payment
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always
  rabbitmq:
    addresses: amqps://sitwvwol:ZJW1odeSgKRgzF2IzTs99mEWYxwXEzMQ@fish.rmq.cloudamqp.com/sitwvwol

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  broker:
    exchange:
      notificationCommandExchange: ead.paymentcommand
    queue:
      notificationCommandQueue:
        name: ead.paymentcommand.ms.payment
    key:
      notificationCommandKey: ms.payment

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
