server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/ead_course_v2
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  rabbitmq:
    addresses: amqps://sitwvwol:ZJW1odeSgKRgzF2IzTs99mEWYxwXEzMQ@fish.rmq.cloudamqp.com/sitwvwol

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    hibernate: INFO

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser/'
  broker:
    exchange:
      userEventExchange: ead.userevent
    queue:
      userEventQueue:
        name: ead.userevent.ms.course

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health